### ISSUE TITLE
Plugin Web Service Data Source

### ISSUE THREAD

**Issue by chiavegatto** [retrievercommunications/docker-jasperserver#11]
I need add plugin Web Service Data Source, but when coppy files to restart container, new configuration jasper-server in tomcat. I need help :)

**Comment by grange74** [comment]
Hi, 
I assume you are following the instructions "Install in TIBCO JasperReports Server" on https://community.jaspersoft.com/wiki/installing-webservice-datasource?
How are you implementing these instructions? by modifying the "entrypoint.sh" or some other way?

Basically from what i see you would need a number of things to add this container image:

- Either download jaspersoft_webserviceds_v1.5.zip, commit to git and add in Dockerfile or dynamically download in Dockerfile and unzip
- open the file WEB-INF\applicationContext-WebServiceDataSource.xml from the unzip folder from previous step. Go to line 49 of the xml file, inside the bean addQueryLanguage change the property beanName from queryLanguagesPro to queryLanguagesCe
- In "entrypoint.sh", after line 28  `./js-ant deploy-webapp-ce`, unzip generated war file (so you don't have to stop/start tomcat), this should be "/usr/local/tomcat/webapps/ROOT.war"
- After previous point in "entrypoint.sh", Copy all the folder's content from [WS_DS_DIR]\JRS\WEB-INF to "/usr/local/tomcat/webapps/ROOT/WEB-INF" folder in the unzipped war

Then when the final line in "entrypoint.sh" (`catalina.sh run`) starts tomcat it should start the jasperserver with the Web Service Datasource plugin available.

Btw, as this would have general applicability, we would welcome a Pull Request for this feature :-).

**Comment by chiavegatto** [comment]
I done add WebServiceDataSource plugin, but i don't permission submit pull request.

https://github.com/chiavegatto/docker-jasperserver

**Comment by grange74** [comment]
Hi @chiavegatto, 
you shouldn't need to have any specific permissions to submit a PR. I've just tried it with a brand new GitHub account, i forked the repo, did a dummy commit, and then created a PR.
What error message are you getting?

**Comment by grange74** [comment]
I was looking at your changes on your fork and they look really good. My main comment is that it would be nice to have each of the changes in separate branches (or atleast commits) instead of all together in one commit on master.
So i would split probably into 3:

- Upgrade to version 6.4.0
- Enable cross-domain Tomcat
- Add Web Service Datasource plugin

This helps with maintaining a clean history by being able to identify why each change was made.

**Comment by grange74** [comment]
PR is now merged in. Thank you @chiavegatto for your contribution!
