### ISSUE TITLE
Two missing bundles

### ISSUE THREAD

**Issue by enfoqueNativo** [retrievercommunications/docker-jasperserver#17]
Hi, 
i've found when trying to access the jasper server via web browser at
`http://localhost:8080/login.html`

there are two missing request that makes the browser stop. The two XHR request are:
`/rest_v2/bundles/AttributeBundle`
`/rest_v2/bundles/CommonBundle`

I've attached output from docker-compose logs 
[log.txt](https://github.com/retrievercommunications/docker-jasperserver/files/1877006/log.txt)

Should i download those bundles manually?
Regards.

**Comment by grange74** [comment]
Hi @enfoqueNativo,
That's strange, they should be there. I created new containers using `docker-compose up` to test and then login page loads fine. I can see in Chrome developer tools that those requests are successful for me.
For me it is trying to access "http://localhost:8080/runtime/AF34530B/rest_v2/bundles/CommonBundle" and a similar url for AttributeBundle.
The only suggestion i can make right now is to try to recreate the containers and see if the problem occurs again. In the past, i've run into run into problems if the jasperserver bootstrap process fails. Recreating the containers will usually fix it.

**Comment by enfoqueNativo** [comment]
Hi @grange74,
you're right.. recreating the containers solved the problem. Thank you!
