### ISSUE TITLE
Jasperserver app is redeployed on every start

### ISSUE THREAD

**Issue by grange74** [retrievercommunications/docker-jasperserver#21]
As spotted by @tariellaelius in https://github.com/retrievercommunications/docker-jasperserver/issues/4#issuecomment-388042429, setting "webAppNameCE" to ROOT in entrypoint.sh in
https://github.com/retrievercommunications/docker-jasperserver/pull/7  means now the app is re-deployed every time the container is restarted because of this line.

**Comment by grange74** [comment]
Thanks for suggesting the fix @tariellaelius, I have implemented it this way. Sorry that you had to spend so much time trying to diagnose the problem. This fix will avoid others having the same problem. Cheers.

**Comment by tariellaelius** [comment]
I'm glad to be helpful. Thank you too for creating this repo!
