### ISSUE TITLE
Support for JasperServer 7.5.0

### ISSUE THREAD

**Issue by kershov** [retrievercommunications/docker-jasperserver#35]
Hi! Could anyone please give some hints on how can this image be upgraded to the latest JasperReports Server version? Thanks!

**Comment by grange74** [comment]
Hi @kershov,

Typically the main change required for a minor version upgrade is to update JASPERSERVER_VERSION environment variable in the Dockerfile. Sometimes it requires an upgrade of the tomcat version. See this example:
https://github.com/retrievercommunications/docker-jasperserver/commit/1a406ef28dd73a5a3b7d6f98f0c1fab30da9d55f

We also update the readme and the docker compose to use the latest version:
https://github.com/retrievercommunications/docker-jasperserver/commit/ad5f4f8566759b34e68e964fe03fa501618dffff

The final step to make the new version available on Dockerhub is to push a new git Tag using the naming convention major.minor.iteration to the repo (as per https://github.com/retrievercommunications/docker-jasperserver#how-to-release-a-new-image-version). This will trigger an automated build and if it succeeds then it should be available in about 10 minutes or so.

Pull requests are welcome.

Cheers,
Nic

**Comment by kershov** [comment]
If someone interested in JRS working with PostgreSQL: https://github.com/kershov/jasperreports
