### ISSUE TITLE
Support for SQL Server

### ISSUE THREAD

**Issue by kamrannawaz** [retrievercommunications/docker-jasperserver#37]
I want to know what changes are needed to support a mssql server container.
Thanks

**Comment by grange74** [comment]
Do you mean as a data source (https://community.jaspersoft.com/wiki/using-ms-sql-server-data-source-jasperreports-server) or for the jasperserver database or both? 

Either way one of the first things to do is add the jdbc driver to the drivers folder
https://github.com/retrievercommunications/docker-jasperserver/tree/master/drivers
and update the docker file to copy it into the container like:
https://github.com/retrievercommunications/docker-jasperserver/blob/master/Dockerfile#L41

**Comment by kamrannawaz** [comment]
> Do you mean as a data source (https://community.jaspersoft.com/wiki/using-ms-sql-server-data-source-jasperreports-server) or for the jasperserver database or both?
> 
> Either way one of the first things to do is add the jdbc driver to the drivers folder
> https://github.com/retrievercommunications/docker-jasperserver/tree/master/drivers
> and update the docker file to copy it into the container like:
> https://github.com/retrievercommunications/docker-jasperserver/blob/master/Dockerfile#L41

yes i tried so many other things & every time i got this type of error whenever i run that image.. i don't know what is this could you plz help me out? what is the problem 
error which i get every time.
standard_init_linux.go:228: exec user process caused: no such file or directory

![git](https://user-images.githubusercontent.com/35919931/129150130-94ab3e37-4459-4365-88fa-4819f1a327d1.JPG)

**Comment by grange74** [comment]
can you please be more specific about what steps/commnads you've done to get that error message?
like are you just trying to run the container or are you rebuilding it? in order to get the drivers in you will need to rebuild the container.

Also please answer the above question about what you are trying to achieve?
> Do you mean as a data source (https://community.jaspersoft.com/wiki/using-ms-sql-server-data-source-jasperreports-server) or for the jasperserver database or both?

**Comment by kamrannawaz** [comment]
> can you please be more specific about what steps/commnads you've done to get that error message?
> like are you just trying to run the container or are you rebuilding it? in order to get the drivers in you will need to rebuild the container.
> 
> Also please answer the above question about what you are trying to achieve?
> 
> > Do you mean as a data source (https://community.jaspersoft.com/wiki/using-ms-sql-server-data-source-jasperreports-server) or for the jasperserver database or both?

i want to run jasper with SQL Server database not with postgress or MySql but with SQL Server i downloaded those jdbc driver for sql server and place them inside the driver folder.
This is the dockerfile which i m using to build image 

FROM tomcat:9.0-jre8
# MAINTAINER Nic Grange nicolas.grange@retrievercommunications.com 

ENV JASPERSERVER_VERSION 7.8.0

# Execute all in one layer so that it keeps the image as small as possible
# RUN wget "https://sourceforge.net/projects/jasperserver/files/JasperServer/JasperReports%20Server%20Community%20Edition%20${JASPERSERVER_VERSION}/TIB_js-jrs_${JASPERSERVER_VERSION}_bin.zip/download" \
#          -O /tmp/jasperserver.zip  && \
#     unzip /tmp/jasperserver.zip -d /usr/src/ && \
#     rm /tmp/jasperserver.zip && \
#     mv /usr/src/jasperreports-server-cp-${JASPERSERVER_VERSION}-bin /usr/src/jasperreports-server && \
#     rm -r /usr/src/jasperreports-server/samples

# RUN wget "https://webwerks.dl.sourceforge.net/project/jasperserver/JasperServer/JasperReports%20Server%20Community%20edition%20${JASPERSERVER_VERSION}/TIB_js-jrs-cp_${JASPERSERVER_VERSION}_bin.zip/download" \
#          -O /tmp/jasperserver.zip  && \
#     unzip /tmp/jasperserver.zip -d /usr/src/ && \
#     rm /tmp/jasperserver.zip && \
#     mv /usr/src/jasperreports-server-cp-${JASPERSERVER_VERSION}-bin /usr/src/jasperreports-server && \
#     rm -r /usr/src/jasperreports-server/samples

COPY ./jasperreports-server-cp-${JASPERSERVER_VERSION}-bin ./usr/src/jasperreports-server
# To speed up local testing
# Download manually the jasperreport server release to working dir
# Uncomment ADD & RUN commands below and comment out above RUN command
# ADD TIB_js-jrs-cp_${JASPERSERVER_VERSION}_bin.zip /tmp/jasperserver.zip
# RUN unzip /tmp/jasperserver.zip -d /usr/src/ && \
#    rm /tmp/jasperserver.zip && \
#    mv /usr/src/jasperreports-server-cp-$JASPERSERVER_VERSION-bin /usr/src/jasperreports-server && \
#    rm -r /usr/src/jasperreports-server/samples

# Used to wait for the database to start before connecting to it
# This script is from https://github.com/vishnubob/wait-for-it
# as recommended by https://docs.docker.com/compose/startup-order/
ADD wait-for-it.sh /wait-for-it.sh

# Used to bootstrap JasperServer the first time it runs and start Tomcat each
ADD entrypoint.sh /entrypoint.sh
ADD .do_deploy_jasperserver /.do_deploy_jasperserver

#Execute all in one layer so that it keeps the image as small as possible
RUN chmod a+x /entrypoint.sh && \
    chmod a+x /wait-for-it.sh

# This volume allows JasperServer export zip files to be automatically imported when bootstrapping
VOLUME ["/jasperserver-import"]

# By default, JasperReports Server only comes with Postgres & MariaDB drivers
# Copy over other JBDC drivers the deploy-jdbc-jar ant task will put it in right location
# ADD drivers/db2jcc4-no-pdq-in-manifest.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/db2jcc4.jar
ADD ./drivers/mssql-jdbc-9.4.0.jre8.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/db2jcc4.jar
ADD ./drivers/mysql-connector-java-5.1.44-bin.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/mysql-connector-java-5.1.44-bin.jar
# ADD drivers/mssql-jdbc-9.4.0.jre11.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/mssql-jdbc-9.4.0.jre11.jar
# ADD drivers/mssql-jdbc-9.4.0.jre16.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/mssql-jdbc-9.4.0.jre16.jar
# Copy web.xml with cross-domain enable
ADD web.xml /usr/local/tomcat/conf/

# Use the minimum recommended settings to start-up
# as per http://community.jaspersoft.com/documentation/jasperreports-server-install-guide/v561/setting-jvm-options-application-servers
ENV JAVA_OPTS="-Xms1024m -Xmx2048m -XX:PermSize=32m -XX:MaxPermSize=512m -Xss2m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

# Wait for DB to start-up, start up JasperServer and bootstrap if required
ENTRYPOINT ["/entrypoint.sh"]

**Comment by kamrannawaz** [comment]
> can you please be more specific about what steps/commnads you've done to get that error message?
> like are you just trying to run the container or are you rebuilding it? in order to get the drivers in you will need to rebuild the container.
> 
> Also please answer the above question about what you are trying to achieve?
> 
> > Do you mean as a data source (https://community.jaspersoft.com/wiki/using-ms-sql-server-data-source-jasperreports-server) or for the jasperserver database or both?

i want to run jasper with SQL Server database not with postgress or MySql but with SQL Server i downloaded those jdbc driver for sql server and place them inside the driver folder.
This is the dockerfile which i m using to build image

FROM tomcat:9.0-jre8

ENV JASPERSERVER_VERSION 7.8.0


COPY ./jasperreports-server-cp-${JASPERSERVER_VERSION}-bin ./usr/src/jasperreports-server



ADD wait-for-it.sh /wait-for-it.sh


ADD entrypoint.sh /entrypoint.sh
ADD .do_deploy_jasperserver /.do_deploy_jasperserver

RUN chmod a+x /entrypoint.sh && \
    chmod a+x /wait-for-it.sh


ADD ./drivers/mssql-jdbc-9.4.0.jre8.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/db2jcc4.jar
ADD ./drivers/mysql-connector-java-5.1.44-bin.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/mysql-connector-java-5.1.44-bin.jar
ADD web.xml /usr/local/tomcat/conf/
application-servers
ENV JAVA_OPTS="-Xms1024m -Xmx2048m -XX:PermSize=32m -XX:MaxPermSize=512m -Xss2m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

ENTRYPOINT ["/entrypoint.sh"]

**Comment by grange74** [comment]
From looking at the installer guide again, only MySQL and PostgreSQL are supported for the Jasperserver database.
You can only use SQL Server for a datasource of one of your reports.

Rebuilding with the above dockerfile should work for using as a datasource. Although you should rename "db2jcc4.jar" in the line below:
> ADD ./drivers/mssql-jdbc-9.4.0.jre8.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/db2jcc4.jar

**Comment by kamrannawaz** [comment]
> From looking at the installer guide again, only MySQL and PostgreSQL are supported for the Jasperserver database.
> You can only use SQL Server for a datasource of one of your reports.
> 
> Rebuilding with the above dockerfile should work for using as a datasource. Although you should rename "db2jcc4.jar" in the line below:
> 
> > ADD ./drivers/mssql-jdbc-9.4.0.jre8.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/app-srv-jdbc-drivers/db2jcc4.jar

i tried with renaming too then i changed it to what driver u putting, btw i want to run jasper with SQL not as a datasource but as a storage db like postgress and mysql, so how want to do that is jasper supports this thing or not or it just use postgress or mysql

**Comment by grange74** [comment]
It is not feasible to make it work with SQL Server. The jasperserver release comes with all sql files to create/update the database but only for MySQL and PostgreSQL under buildomatic/install_resources/sql. Even if you created all the sql server equivalent, the other problem is that it hasn't been tested with SQL server so if you come across any errors you will have to fix the code yourself.
