### ISSUE TITLE
Persistency issues

### ISSUE THREAD

**Issue by cemo** [retrievercommunications/docker-jasperserver#6]
Is all data stored in database right now? I mean if I start my container again, will I lose something regarding data? 

I think that this is worth that to be stated in `README` as well.

**Comment by grange74** [comment]
Yes, i believe data should all be stored in the DB. Though to be honest i haven't done extensive testing on this as it has mainly been used for development where long term persistence isn't so important.

From my understanding if you stop and start the containers again you shouldn't lose anything. Also if you delete the jasperserver container and then create it but point to the same database container then it should be keep everything as is. Like if want to upgrade the version of the jasperserver container.
Obviously if you delete the database container and recreate it then you will have to of mounted the appropriate data directory beforehand for it to survive the recreation of the container.

I agree that it would helpful to have more information about this in the readme. I'll see what i can come up with in the next few days. I'd welcome any suggestions or PRs.

**Comment by cemo** [comment]
Thanks for clarification. I have deleted my container and created again. It seems that there is no loss.
